# Generated by Django 2.0.4 on 2018-04-23 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrummyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('task_id', models.IntegerField(default=700)),
                ('time_of_status_change', models.DateTimeField(default=datetime.datetime.now)),
                ('moved_by', models.CharField(default='not moved yet', max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('movement_track', models.IntegerField(default=1234)),
            ],
        ),
        migrations.CreateModel(
            name='Scrumystatus',
            fields=[
                ('status', models.CharField(choices=[('DT', 'daily task'), ('V', 'Verified'), ('WT', 'weekly Task'), ('D', 'Done')], max_length=50, primary_key=1, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scrumyuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=20)),
                ('Owner', models.CharField(default='Owner', max_length=200)),
                ('Admin', models.CharField(default='Admin', max_length=200)),
                ('QA', models.CharField(default='QA', max_length=200)),
                ('Developer', models.CharField(default='Developer', max_length=200)),
            ],
            options={
                'verbose_name': 'Scrumyuser',
            },
        ),
        migrations.AddField(
            model_name='scrummygoals',
            name='danny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Scrumyuser'),
        ),
        migrations.AddField(
            model_name='scrummygoals',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.Scrumystatus'),
        ),
    ]
