# Generated by Django 2.0.4 on 2018-04-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dannyscrumy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(default='verified', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scrummygoals',
            options={'verbose_name_plural': 'ScrumyGoals'},
        ),
        migrations.AlterModelOptions(
            name='scrumystatus',
            options={'verbose_name_plural': 'Scrumystatus'},
        ),
        migrations.AlterField(
            model_name='scrumystatus',
            name='status',
            field=models.CharField(choices=[('V', 'Verified'), ('WT', 'weekly Task'), ('D', 'Done'), ('DT', 'daily task')], max_length=50, primary_key=1, serialize=False),
        ),
        migrations.AddField(
            model_name='goalstatus',
            name='daily_target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dannyscrumy.ScrummyGoals'),
        ),
    ]
